/// Generated by Flutter GetX Starter on 2022-09-05 15:53
import 'package:get/get.dart';
import 'package:zarfilm_android_tv/app/common/RequestInterface.dart';

import '../../../gen/json/base/HomeJsonDataModel.dart';
import 'home_state.dart';

class HomeLogic extends GetxController implements RequestInterface {
  final state = HomeState();


  HomeLogic();


  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }

  @override
  void onError(String content, int reqCode, String bodyError) {
    // TODO: implement onError
  }

  @override
  void onStartReuqest(int reqCode) {
    // TODO: implement onStartReuqest
  }

  @override
  void onSucces(source, int reqCdoe) {
    // TODO: implement onSucces
  }
}