import 'package:get/get.dart';

import '../../../gen/json/base/FromJsonSplash.dart';
import '../../../gen/json/base/HomeJsonDataModel.dart';

/// Generated by Flutter GetX Starter on 2022-09-05 15:53
class HomeState {
  HomeJsonDataModel homeJsonDataModel = new HomeJsonDataModel();
  FromJsonSplash fromJsonSplash = new FromJsonSplash();
  var mainSug = new Suggestions().obs;
  var genreIndex = 0.obs;


  HomeState() {
    ///Initialize variables
  }
}
