/// Generated by Flutter GetX Starter on 2022-09-05 15:53
import 'package:get/get.dart';

import 'home_state.dart';

class HomeLogic extends GetxController {
  final state = HomeState();

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}