/// Generated by Flutter GetX Starter on 2022-09-05 15:53
import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_svg/svg.dart';
import 'package:get/get.dart';
import 'package:sizer/sizer.dart';
import 'package:text_scroll/text_scroll.dart';
import 'package:widget_slider/controller.dart';
import 'package:widget_slider/widget_slider.dart';
import 'package:zarfilm_android_tv/app/common/app_color.dart';

import '../../common/app_icons.dart';
import 'home_logic.dart';
import 'home_state.dart';

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final HomeLogic logic = Get.put(HomeLogic());
  final HomeState state = Get.find<HomeLogic>().state;

  @override
  void dispose() {
    Get.delete<HomeLogic>();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final controller = SliderController(
      duration: const Duration(milliseconds: 600),
    );

    final images = const [
      'https://i.picsum.photos/id/816/200/300.jpg?hmac=4O5XSGjimzcjZYOXpVb_--v3rGzmS-3chmG2L1MS-mc',
      'https://i.picsum.photos/id/436/200/300.jpg?hmac=OuJRsPTZRaNZhIyVFbzDkMYMyORVpV86q5M8igEfM3Y',
      'https://i.picsum.photos/id/645/200/300.jpg?hmac=fiKW3Nj8r0CWJQY3S-kkeT8PAfvKhA8igd9GIRk41Yw',
      'https://i.picsum.photos/id/281/200/300.jpg?hmac=KCN8F5QTgxHdeQxLpZ5BOuUEVQEp8jAedlLSRERW7CY',
      'https://i.picsum.photos/id/816/200/300.jpg?hmac=4O5XSGjimzcjZYOXpVb_--v3rGzmS-3chmG2L1MS-mc',
    ];

    SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      systemNavigationBarColor: Colors.transparent,
    ));
    return Scaffold(
      backgroundColor: "191919".toColor(),
      body: SafeArea(
        child: Container(
          // padding: EdgeInsets.fromLTRB(16, 16, 16, 0),
          child: Column(
            children: [
              Container(
                padding: EdgeInsets.fromLTRB(16, 0, 16, 0),
                height: 9.h,
                child: Stack(
                  children: [
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Container(
                          width: 8.w,
                          height: 8.w,
                          decoration: BoxDecoration(
                              border: Border.all(
                                  color: Colors.white.withOpacity(0.3),
                                  width: 2),
                              borderRadius: BorderRadius.circular(10)),
                          padding: EdgeInsets.all((1.5).w),
                          child: MaterialButton(
                              padding: EdgeInsets.zero,
                              shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(10)),
                              onPressed: () {},
                              child: SvgPicture.string(
                               IconsAll.user,
                                color: Colors.white,
                              )),
                        ),
                        Row(
                          children: [
                            Container(
                              width: 8.w,
                              height: 8.w,
                              decoration: BoxDecoration(
                                  border: Border.all(
                                      color: Colors.white.withOpacity(0.3),
                                      width: 2),
                                  borderRadius: BorderRadius.circular(10)),
                              padding: EdgeInsets.all((1).w),
                              child: MaterialButton(
                                  padding: EdgeInsets.zero,
                                  shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10)),
                                  onPressed: () {},
                                  child: SvgPicture.asset(
                                    "assets/image/flaticon-2811806-magnifying-glass.svg",
                                    color: Colors.white,
                                  )),
                            ),
                            SizedBox(
                              width: 3.w,
                            ),
                            Container(
                              width: 8.w,
                              height: 8.w,
                              decoration: BoxDecoration(
                                  border: Border.all(
                                      color: Colors.white.withOpacity(0.3),
                                      width: 2),
                                  borderRadius: BorderRadius.circular(10)),
                              padding: EdgeInsets.all((1.5).w),
                              child: MaterialButton(
                                  padding: EdgeInsets.zero,
                                  shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10)),
                                  onPressed: () {},
                                  child: SvgPicture.asset(
                                    "assets/image/flaticon-747327-menu.svg",
                                    color: Colors.white,
                                  )),
                            ),
                          ],
                        ),
                      ],
                    ),
                    Align(
                      alignment: Alignment.topCenter,
                      child: Image.asset(
                        "assets/image/logo.png",
                        height: 5.h,
                        width: 5.h,
                      ),
                    )
                  ],
                ),
              ),
              WidgetSlider(
                fixedSize: 200,
                infiniteScroll: true,

                proximity: 0.35,
                controller: controller,
                itemCount: images.length,
                itemBuilder: (context, index, activeIndex) {
                  return Container(
                    margin: const EdgeInsets.all(5),
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(10),
                      image: DecorationImage(
                        fit: BoxFit.fill,
                        image: NetworkImage(images[index]),
                      ),


                    ),
                  );
                },
              ),
              Container(
                padding: EdgeInsets.symmetric(horizontal: 6.w,vertical: 2.h),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Column(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Container(width: 8.w,height: 8.w,
                        decoration: BoxDecoration(
                          color: AppColor.praimaryColor.withOpacity(0.1),
                          borderRadius: BorderRadius.circular(10)
                        ),
                        padding: EdgeInsets.all((1.8).w),
                        child: Center(
                          child: SvgPicture.asset("assets/image/flaticon-2617271-play-button.svg",color: AppColor.praimaryColor,),
                        ),
                        ),
                        SizedBox(height: 4,),
                        Row(
                          children: [
                            Text("TOP",style: TextStyle(color: AppColor.praimaryColor),),
                            Text("10",style: TextStyle(color: Colors.white),),
                          ],
                        ),
                        SizedBox(height: 6,),

                        Text("Series",style: TextStyle(color: Colors.white.withOpacity(0.5),fontWeight: FontWeight.w200),),

                      ],
                    ),
                    Expanded(child: Container(
                      margin: EdgeInsets.symmetric(horizontal: 4.w),
                      child: Column(
                        children: [
                          TextScroll("She-Hulk: Attorney at Law She-Hulk: Attorney at Law"
                            ,style: TextStyle(fontWeight: FontWeight.bold),
                            delayBefore: Duration(
                              milliseconds: 300,
                            ),

                          ),
                          Text("2022",style: TextStyle(fontWeight: FontWeight.w200),),
                        ],
                      ),
                    )),
                    Column(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Container(width: 8.w,height: 8.w,
                        decoration: BoxDecoration(
                          color: AppColor.praimaryColor.withOpacity(0.1),
                          borderRadius: BorderRadius.circular(10)
                        ),
                        padding: EdgeInsets.all((1.8).w),
                        child: Center(
                          child: SvgPicture.asset("assets/image/flaticon-2550223-favorite.svg",color: AppColor.praimaryColor,),
                        ),
                        ),
                        SizedBox(height: 4,),
                        Row(
                          children: [
                            Text("9.2",style: TextStyle(color: AppColor.praimaryColor),),
                            Text(" /10",style: TextStyle(color: Colors.white),),
                          ],
                        ),
                        SizedBox(height: 6,),

                        Text("498/200",style: TextStyle(color: Colors.white.withOpacity(0.5),fontWeight: FontWeight.w200),),

                      ],
                    ),
                  ],
                ),
              ),
              Padding(
                padding: EdgeInsets.fromLTRB(2.w, 0, 2.w, 0),
                child: Column(
                  children: [
                    Container(
                      width: 100.w,
                      decoration: BoxDecoration(
                        color: "ffc64b".toColor(),
                        borderRadius: BorderRadius.circular(10)
                      ),
                      padding: EdgeInsets.all(2.w),
                      child: Directionality(

                          textDirection: TextDirection.rtl,child: Text("دانلود و تماشا فقط با IP ایران امکان پذیر هست.",style: TextStyle(
                        color: "3d3d3d".toColor()
                      ),)),
                    ),
                    SizedBox(height: 2.h,),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Container(
                          width: 15.w,
                          height: 4.h,
                          decoration: BoxDecoration(
                              color: "212121".toColor(),
                            borderRadius: BorderRadius.circular(100)
                          ),
                          child: Center(
                            child:  Text("بیشتر",style: TextStyle(color: Colors.white.withOpacity(0.5)),),
                          ),
                        ),
                        Text("سریال های بروز شده",style: TextStyle(color: Colors.white.withOpacity(0.5)),),

                      ],
                    ),

                  ],
                ),
              ),
              Padding(
                padding: EdgeInsets.only(right: 2.w),
                child: Directionality(
                  textDirection: TextDirection.rtl,
                  child: Container(
                    width: 100.w,
                    margin: EdgeInsets.symmetric(vertical: 2.h),
                    child: SingleChildScrollView(
                      scrollDirection: Axis.horizontal,
                      child: Row(

                        children:[
                          Container(
                            margin: EdgeInsets.only(left: 4.w),
                            width: 80.w,
                            height: 20.h,
                            child: MaterialButton(
                              onPressed: (){},
                              padding: EdgeInsets.zero,
                              child: Stack(
                                children: [
                                  Align(
                                    alignment: Alignment.topRight,

                                    child:Container(
                                      width: 80.w,
                                      height: 16.h,
                                      child: ClipRRect(
                                          borderRadius: BorderRadius.circular(10),
                                          child: Image.network("https://i.picsum.photos/id/816/200/300.jpg?hmac=4O5XSGjimzcjZYOXpVb_--v3rGzmS-3chmG2L1MS-mc",fit: BoxFit.cover,)),
                                    ) ,
                                  ),
                                  Align(
                                    alignment: Alignment.bottomLeft,

                                    child:Container(

                                        child: Text("She-Hulk: Attorney at Law ")

                                    ) ,
                                  ),
                                  Align(
                                    alignment: Alignment.bottomRight,

                                    child:Container(
                                      height: 4.h,
                                      margin: EdgeInsets.only(
                                          bottom: 2.h,
                                          right: 2.w
                                      ),
                                      decoration: BoxDecoration(
                                          color: "121b20".toColor(),
                                          borderRadius: BorderRadius.circular(5)

                                      ),
                                      padding: EdgeInsets.all(3),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        children: [
                                          Text("فصل اول",style: TextStyle(
                                              fontWeight: FontWeight.bold,
                                              fontSize: 9.sp
                                          ),),
                                          SizedBox(width: 2.w,),
                                          Container(
                                            padding: EdgeInsets.all(4),

                                            decoration: BoxDecoration(
                                                color: AppColor.praimaryColor,
                                                borderRadius: BorderRadius.circular(5)
                                            ),
                                            child:  Text("فصل اول",style: TextStyle(
                                                fontWeight: FontWeight.bold,
                                                fontSize:8.sp,

                                                color: Colors.white
                                            ),),
                                          )
                                        ],
                                      ),
                                    ) ,
                                  ),
                                ],
                              ),
                            ),
                          ),
                          Container(
                            margin: EdgeInsets.only(left: 4.w),
                            width: 80.w,
                            height: 20.h,
                            child: Stack(
                              children: [
                                Align(
                                  alignment: Alignment.topRight,

                                  child:Container(
                                    width: 80.w,
                                    height: 16.h,
                                    child: ClipRRect(
                                        borderRadius: BorderRadius.circular(10),
                                        child: Image.network("https://i.picsum.photos/id/816/200/300.jpg?hmac=4O5XSGjimzcjZYOXpVb_--v3rGzmS-3chmG2L1MS-mc",fit: BoxFit.cover,)),
                                  ) ,
                                ),
                                Align(
                                  alignment: Alignment.bottomLeft,

                                  child:Container(

                                      child: Text("She-Hulk: Attorney at Law ")

                                  ) ,
                                ),
                                Align(
                                  alignment: Alignment.bottomRight,

                                  child:Container(
                                    height: 4.h,
                                    margin: EdgeInsets.only(
                                        bottom: 2.h,
                                        right: 2.w
                                    ),
                                    decoration: BoxDecoration(
                                        color: "121b20".toColor(),
                                        borderRadius: BorderRadius.circular(5)

                                    ),
                                    padding: EdgeInsets.all(3),
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      children: [
                                        Text("فصل اول",style: TextStyle(
                                            fontWeight: FontWeight.bold,
                                            fontSize: 9.sp
                                        ),),
                                        SizedBox(width: 2.w,),
                                        Container(
                                          padding: EdgeInsets.all(4),

                                          decoration: BoxDecoration(
                                              color: AppColor.praimaryColor,
                                              borderRadius: BorderRadius.circular(5)
                                          ),
                                          child:  Text("فصل اول",style: TextStyle(
                                              fontWeight: FontWeight.bold,
                                              fontSize:8.sp,

                                              color: Colors.white
                                          ),),
                                        )
                                      ],
                                    ),
                                  ) ,
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}
