/// Generated by Flutter GetX Starter on 2022-09-05 15:53
import 'package:flutter/foundation.dart';

class Constant {
  /// kReleaseMode是release模式constant下的一个常量
  static const String HTTP_HOST = kReleaseMode ? 'https://zarfilmapp.com/wp-json/zarfilm/v2/route/' : 'https://zarfilmapp.com/wp-json/zarfilm/v2/route/';
  /// 原生-flutter交互 channel
  static const String ZHIQ_FLUTTER_CHANNEL = 'zhiq_flutter_channel';
}

/// 设计图尺寸用于屏幕适配
class Design {
  static const double width = 750;
  static const double height = 1334;
}
