/// Generated by Flutter GetX Starter on 2022-09-05 15:53
import 'dart:io';
import 'package:flutter/widgets.dart';

extension FontWeightExtension on FontWeight {
  FontWeight get auto {
    if (Platform.isAndroid && this == FontWeight.bold) {
      return FontWeight.w500;
    }
    return this;
  }
}