/// Generated by Flutter GetX Starter on 2022-09-05 15:53
import 'package:dart_ipify/dart_ipify.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class Constant {
  /// kReleaseMode是release模式constant下的一个常量
  static const String HTTP_HOST = kReleaseMode ? 'https://zarfilmapp.com/wp-json/zarfilm/v2/route/' : 'https://zarfilmapp.com/wp-json/zarfilm/v2/route/';
  /// 原生-flutter交互 channel
  static const String ZHIQ_FLUTTER_CHANNEL = 'zhiq_flutter_channel';

  static void showMessege(messege)async{
    ScaffoldMessenger.of(Get.context!).showSnackBar(
        SnackBar(content: Text(messege,textAlign: TextAlign.right,style: TextStyle(
            fontFamily: "Schyler"
        ),))
    );
  }
  static void hideKeyboard(BuildContext context) {
    FocusScopeNode currentFocus = FocusScope.of(context);
    if (!currentFocus.hasPrimaryFocus && currentFocus.focusedChild != null) {
      FocusManager.instance.primaryFocus?.unfocus();
    }
  }
  static Future<String> getIP()async{
    final ipv4 = await Ipify.ipv4();

    return ipv4;
  }
}

/// 设计图尺寸用于屏幕适配
class Design {
  static const double width = 750;
  static const double height = 1334;
}

class GetRtlWidget extends StatelessWidget{

  final Widget child;

  const GetRtlWidget({ required this.child}) : super();

  @override
  Widget build(BuildContext context) {

    return Directionality(textDirection: TextDirection.rtl,
        child:
        this.child
    );
    return child;

  }




}
class GetLTRWidget extends StatelessWidget{

  final Widget child;

  const GetLTRWidget({ required this.child}) : super();

  @override
  Widget build(BuildContext context) {

    return Directionality(textDirection: TextDirection.ltr,
        child:
        this.child
    );
    return child;

  }




}
