/// Generated by Flutter GetX Starter on 2022-09-05 15:53
import 'package:get/get.dart';
import 'package:zarfilm_android_tv/app/pages/home/home_page.dart';
import 'package:zarfilm_android_tv/app/pages/login/view.dart';
import 'package:zarfilm_android_tv/app/pages/single_movie/view.dart';

import '../pages/splash/view.dart';

class Routes {
  static const HOME = '/home';
  static const LOGIN = '/login';
  static const SPLASH = '/splash';
  static const SINGLEMOVIE = '/SingleMovie';

  static final routes = [
    GetPage(
      name: Routes.HOME,
      page: () => HomePage(),
    ),
    GetPage(
      name: Routes.LOGIN,
      page: () => LoginPage(),
    ),
    GetPage(
      name: Routes.SPLASH,
      page: () => SplashPage(),
    ),
    GetPage(
      name: Routes.SINGLEMOVIE,
      page: () => SingleMoviePage(),
    ),
  ];
}