/// Generated by Flutter GetX Starter on 2022-09-05 15:53
import './utils/http.dart';

class Api {
  static Future<dynamic> getHome(test) async {
    // Map data = await Http.get(
    //   "/example/home/0.1.0/getHome",
    //   params: {"test": test},
    // );
    Map data = {

  };
    return data;
  }
}
